name: Deploy
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_FRONT }}
          password: ${{ secrets.DOCKERHUB_PASSWORD_FRONT }}
      - name: Create .env.Local file
        run: |
          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET_FRONT }}" >> .env.local
          echo "HOST_URL=${{ secrets.HOST_URL_FRONT }}" >> .env.local
          echo "API_BASE_URL=${{ secrets.BASE_URL_FRONT }}" >> .env.local

      - name: Build the Docker image
        run: docker build -t ajvls98/nextjs-app .

      - name: Tag the Docker image
        run: docker tag ajvls98/nextjs-app:latest ajvls98/nextjs-app:latest

      - name: Push to DockerHub
        run: docker push ajvls98/nextjs-app:latest
