name: CD

on:
  workflow_run:
    workflows: [Deploy]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull ajvls98/nextjs-app:latest

      - name: Stop and Remove Old Docker container
        run: |
          sudo docker stop nextjs-app || true
          sudo docker rm nextjs-app || true

      - name: Run Docker container
        run: sudo docker run -d -p 3000:3000 --name nextjs-app ajvls98/nextjs-app:latest
