name: CD Pipeline

on:
  push:
    branches:
      - test/deploy

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_FRONT }}
          password: ${{ secrets.DOCKERHUB_PASSWORD_FRONT }}

      - name: Build the Docker image
        run: docker build -t ajvls98/nextjs-app .

      - name: Tag the Docker image
        run: docker tag ajvls98/nextjs-app:latest ajvls98/nextjs-app:latest

      - name: Push to DockerHub
        run: docker push ajvls98/nextjs-app:latest

      - name: Pull Docker image
        run: sudo docker pull ajvls98/nextjs-app:latest

      - name: Stop and Remove Old Docker container
        run: |
          sudo docker stop nextjs-app || true
          sudo docker rm nextjs-app || true

      - name: Run Docker container
        run: sudo docker run -d -p 3000:3000 --name nextjs-app ajvls98/nextjs-app:latest
