name: CD

on:
  workflow_run:
    workflows: ['Deploy']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull ajvls98/nextjs-app:latest

      - name: Create .env.local file
        run: |
          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET_FRONT }}" >> .env.local
          echo "HOST_URL=${{ secrets.HOST_URL_FRONT }}" >> .env.local
          echo "API_BASE_URL=${{ secrets.API_BASE_URL_FRONT }}" >> .env.local

      - name: Stop and Remove Old Docker container
        run: |
          sudo docker stop nextjs-app || true
          sudo docker rm nextjs-app || true

      - name: Run Docker container
        run: sudo docker run -d -p 3000:3000 --env-file .env.local --name nextjs-app ajvls98/nextjs-app:latest
