name: Deploy
on:
  push:
    branches:
      - test/deploy
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2
      - name: Check Node v
        run: node -v
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: zip create
        run: zip -qq -r ./test-build.zip .
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_FRONT }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_FRONT }}
          aws-region: ${{ secrets.AWS_REGION_FRONT }}
      - name: Upload to S3
        run: |
          aws s3 cp --region ap-southeast-2 ./test-build.zip s3://kano-nextjs-s3/test-build.zip
      - name: Deploy
        run: |
          aws deploy create-deployment \
            --application-name kano-nextjs-code-deploy \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name kano-nextjs-group \
            --s3-location bucket=kano-nextjs-s3,key=test-build.zip,bundleType=zip
